name: EXAMPLE

on:
  push:
    branches:
      - branch1         # Push events on master branch
jobs:
  build:
    env:
      JOB_RESULT: 0
    runs-on: ubuntu-latest

    steps:
      # Checking out
      - uses: actions/checkout@v2
    
      # Setting up JDK
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      # The following generates a debug APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      
