name: EXAMPLE

on:
  push:
    branches:
      - branch1         # Push events on master branch
jobs:
  build:
    env:
      JOB_RESULT: 0
    runs-on: ubuntu-latest

    steps:
      # Setting up JDK
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      # The following generates a debug APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      
      - name: Check build result1
        run: |
          echo ${JOB_RESULT}
          echo "::set-env name=JOB_RESULT::1"
          echo ${JOB_RESULT}
          echo "::set-env name=JOB_RESULT::2"
          echo ${JOB_RESULT}

      - name: Check build result2
        if: env.JOB_RESULT==2
        run: |
          echo ${JOB_RESULT}

      - name: Check build result3
        if: env.JOB_RESULT==1
        run: |
          echo ${JOB_RESULT}
