name: EXAMPLE

on:
  push:
    branches:
      - branch1         # Push events on master branch
jobs:
  build:
    env:
      JOB_RESULT: 0
    runs-on: ubuntu-latest

    steps:
      # Checking out
      - uses: actions/checkout@v2
    
      # Setting up JDK
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      ###############################################
      - name: Update secret key
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: echo SECRET_KEY="$SECRET_KEY" >> ./debug.properties |
          echo SAMPLE_KEY=-DEBUG >> ./debug.properties
      ###############################################

      - run: echo aiueo=1 >> ./debug.properties |
         echo kakikukeko=2 >> ./debug.properties

      # - run: touch ./local.properties
      
      # The following generates a debug APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug


      - uses: pCYSl5EDgo/cat@master
        id: hello
        with:
          path: ./local.properties

      - run: echo $TEXT
        env:
          TEXT: ${{ steps.hello.outputs.text }}

      - name: Archive apk
        uses: actions/upload-artifact@v1
        with:
          name: debug_apk
          path: app/build/outputs/apk/debug/app-debug.apk

      
